### ISSUE TITLE
u120362

### ISSUE THREAD

**Issue by javig13** [FacultadInformatica-LinkedData/Curso2016-2017#166]
![u120362](https://cloud.githubusercontent.com/assets/22473826/18892139/a1c588fe-8508-11e6-87ba-3652f22dfbad.jpeg)

**Comment by javig13** [comment]
<?xml version="1.0"?>
    <rdf:RDF
    xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
     xmlns:class="http://www.ontologies.org/ontologies/class#"
     xmlns:sensor="http://www.ontologies.org/ontologies/sensor#"
     xmlns:computer="http://www.ontologies.org/ontologies/computer#"
     xmlns:measurement="http://www.ontologies.org/ontologies/measurement#"
     xmlns:owner="http://www.ontologies.org/ontologies/owner#"
     xmlns="http://www.oeg-upm.net/ontologies/class#"
    xml:base="http://www.oeg-upm.net/ontologies/class">

```
<rdf:Property rdf:about="http://www.ontologies.org/ontologies/class#includes"/>
<rdf:Property rdf:about="http://www.ontologies.org/ontologies/sensor#hasMeasurement"/>
<rdf:Property rdf:about="http://www.ontologies.org/ontologies/measurement#hasTemperature"/>
<rdf:Property rdf:about="http://www.ontologies.org/ontologies/measurement#atTime"/>
<rdf:Property rdf:about="http://www.ontologies.org/ontologies/computer#hasOwner"/>
<rdf:Property rdf:about="http://www.ontologies.org/ontologies/owner#hasName"/>


<rdf:Description rdf:about="#Class01">
<class:involves rdf:resource="#Sensor029"/>
<class:involves rdf:resource="#Computer101"/>
</rdf:Description>
```

<rdf:Description rdf:about="#Sensor029">
<sensor:hasMeasurement rdf:resource="Measurement8041"/>
/rdf:Description

<rdf:Description rdf:about="#Computer101">
<computer:hasOwner rdf:resource="User10A"/>
/rdf:Description

<rdf:Description rdf:about="Measurement8041">
measurement:hasTemperature:19/measurement:hasTemperature
measurement:atTime2010-06-12T12:00:12/measurement:atTime
/rdf:Description

<rdf:Description rdf:about="User10A">
user:hasNamePedro/user:hasName
/rdf:Description
/rdf:RDF

@base http://www.oeg-upm.net/ontologies/class/ .
@prefix vocab: http://www.ontologies.org/ontologies/class# .

:Class01    vocab:includes :Sensor029 ;
            vocab:includes :Computer101 .

:Sensor029  vocab:hasMeasurement :Measurement8401 .
:Measurement8401    vocab:hasTemperature "29"^^xsd:int ;
                    vocab:atTime "2010-06-12T12:00:12"^^xsd:dateTime .
:Computer101        vocab:hasOwner :User10A .

:User10A    vocab:hasName "Pedro"^^xsd:string .

**Comment by javig13** [comment]
@base http://www.oeg-upm.net/ontologies/class/ .
@prefix vocab: http://www.ontologies.org/ontologies/class# .

:Class01    vocab:includes :Sensor029 ;
            vocab:includes :Computer101 .

:Sensor029  vocab:hasMeasurement :Measurement8401 .
:Measurement8401    vocab:hasTemperature "29"^^xsd:int ;
                    vocab:atTime "2010-06-12T12:00:12"^^xsd:dateTime .
:Computer101        vocab:hasOwner :User10A .

:User10A    vocab:hasName "Pedro"^^xsd:string .

**Comment by idafensp** [comment]
Why have you created an issue?

**Comment by javig13** [comment]
yesterday i had a problem with the uploading of the second assigment. i talked to a friend asking for a solution, and understood that i had to upload it on a issue. That wasnt what he was explaining me... Now i dont know if i have uploaded correctly the files.

Im sorry.

---

De: Idafen Santana Pérez notifications@github.com
Enviado: miércoles, 28 de septiembre de 2016 11:32
Para: FacultadInformatica-LinkedData/Curso2016-2017
Cc: javig13; Author
Asunto: Re: [FacultadInformatica-LinkedData/Curso2016-2017] u120362 (#166)

Why have you created an issue?

##

**Comment by idafensp** [comment]
Don't worry, I was just curious. I'll take a look and check your files, don't worry.

**Comment by javig13** [comment]
As i see on the asigment 2 folder, my files havent been uploaded.

---

De: Idafen Santana Pérez notifications@github.com
Enviado: miércoles, 28 de septiembre de 2016 12:01
Para: FacultadInformatica-LinkedData/Curso2016-2017
Cc: javig13; Author
Asunto: Re: [FacultadInformatica-LinkedData/Curso2016-2017] u120362 (#166)

Don't worry, I was just curious. I'll take a look and check your files, don't worry.

##
