### ISSUE TITLE
Problema al subir la tarea 2

### ISSUE THREAD

**Issue by davidamb** [FacultadInformatica-LinkedData/Curso2016-2017#198]
Hola:
He tenido un problema con la tarea 2. Ayer hice el pull request, comprobé que estaba en la lista de  pull requests y aparecía. Esta tarde cuando he visto los archivos de la carpeta de la tarea 2 los mios no aparecían.  El identificador del pull request es: #88. Quería saber cual ha sido el problema y si puedo subirlos de nuevo. 

Saludos y perdón las molestias,
David

**Comment by nandana** [comment]
Hola David, 

Tu pull request esta abierta todovia y no hicimos el merge porque los ficheros no estan nombrado con tu usario del GitHub. En lugar de "davidamran.rdf", usa "davidamb.rdf". 

Si necesitas algun ayuda, let us know!

Las instrucciones son:

Exercise on RDF and RDFS. Upload the RDF and RDFS files corresponding to the exercise in the GitHub repository, and comment on those from your colleagues, creating issues in the GitHub repository. This can be done in the Assignment2 folder, using your GitHub username + .rdf and .rdfs, or any other similar file extension.

For example, I (my Github username is 'nandana') will upload three files :

nandna.png (the image, Exercise 1.a)
nandana.rdf (Exercise 1.b in RDF/XML), and
nandana.ttl (Exercise 1.b in Turtle).

Un saludo,
Nandana

**Comment by davidamb** [comment]
Vale. Gracias. Ya están actualizados el nombre de los archivos.

**Comment by nandana** [comment]
Merged the pull request.
