### ISSUE TITLE
Duda en el Assigment 3

### ISSUE THREAD

**Issue by PabloFdez** [FacultadInformatica-LinkedData/Curso2016-2017#205]
Según la solución que se propuso en clase la tarea 3.2 se solucionaba de la siguiente forma:

// *\* TASK 2.3: Add Jane as a person who John knows through an object
property from the FOAF vocabulary**

Property knows = model.createProperty(foafNS+"knows");
johnSmith.addProperty(knows, janeSmith);

En cambio, en clase yo la hice así:

janeSmith.addProperty(FOAF.knows, fullName);

(Siendo fullName el nombre de John)

¿Se puede hacer de las dos formas?

**Comment by nandana** [comment]
Hola Pablo,

Si, los dos formas son correctos y como tu has hecho es mejor en este caso. La solucion tiene asi para ensenar como declarar una propidad pero en este caso concrete no es necesario.

Un saludo,
Nandanaf
