### ISSUE TITLE
No me deja subir archivos

### ISSUE THREAD

**Issue by QitingLiHu** [FacultadInformatica-LinkedData/Curso2016-2017#230]
Hola,
No me deja hacer upload de archivos me dice: File uploads require push access to this repository. En el assignment 2

**Comment by nandana** [comment]
Hola Qiting,

Estas entando hacer upload en tu repo:
https://github.com/QitingLiHu/Curso2016-2017/tree/master/Assignment2

o en repo de clase:
https://github.com/FacultadInformatica-LinkedData/Curso2016-2017/tree/master/Assignment2

En tuyo, tienes que tener derecho a subir y luego puedes hacer un pull request. Avisanos si se puede. 

Un saludo,
Nandana

**Comment by QitingLiHu** [comment]
Vale, es que lo estaba haciendo directamente en repo de clase, ya he hecho el pull request. Muchas gracias!

**Comment by nandana** [comment]
De nada. Ya esta acepetado el pull request #231 .

Un saludo,
Nandana
