### ISSUE TITLE
Como actualizar mi repositorio a la nueva version directamente desde la web sin utilizar comandos?

### ISSUE THREAD

**Issue by davidamb** [FacultadInformatica-LinkedData/Curso2016-2017#264]
Hola:

Necesito actualizar el repositorio para poder entregar la tarea de jena y no se como hacerlo. ¿En donde hay que poner los comandos esos que pone en la web? o ¿es posible hacerlo directamente desde la web sin utilizar comandos?

Saludos,
David

**Comment by nandana** [comment]
Hola David,

Si, puede hacer desde web sin commandos. Tienes que crear un pull request, pero desde el repo de clase a tu fork. Este enlace describe como hacerlo. Si tienes dudas, preguntame de nuevo.

[https://www.sitepoint.com/quick-tip-sync-your-fork-with-the-original-without-the-cli/](https://www.sitepoint.com/quick-tip-sync-your-fork-with-the-original-without-the-cli/)

Un saludo,
Nandana

**Comment by rgcmme** [comment]
It seems that this was solved.
