### ISSUE TITLE
Problema al generar RDF as Turtle

### ISSUE THREAD

**Issue by javierdlrm** [FacultadInformatica-LinkedData/Curso2016-2017#431]
Según indican las diapositivas vistas en clase, previo a la exportación 'RDF as Turtle' hay que editar el RDF Schema, pero al hacer click en Extensions: RDF -> Edit Skeleton no aparece la ventana de RDF Schema Alignment ni se produce ninguna otra respuesta.

¿Cuál puede ser la causa?

**Comment by rgcmme** [comment]
Comprueba que la extensión de RDF esté correctamente instalada. Puede que sea eso.

**Comment by rgcmme** [comment]
It seems that the issue has been solved.

**Comment by javierdlrm** [comment]
En la versión anterior de LodRefine si funciona.
