### ISSUE TITLE
Assigment5 - No genera ttl

### ISSUE THREAD

**Issue by VictorViller** [FacultadInformatica-LinkedData/Curso2016-2017#467]
[mapping.ttl.zip](https://github.com/FacultadInformatica-LinkedData/Curso2016-2017/files/617075/mapping.ttl.zip)

**Comment by nandana** [comment]
@fpriyatna Can you please have a look at this when you got sometime to see if there is a problem in mappingpdia side?

**Comment by fpriyatna** [comment]
can somebody please provide me the database information

**Comment by nandana** [comment]
@fpriyatna here's the database configuration.

https://github.com/nandana/wsyld16-morph/blob/master/handson/config.properties

**Comment by fpriyatna** [comment]
hi all,

Attached is the correct mappings.

Some notes:
- TriplesMap LinkMap_1_3 is not valid, there is no table city_countrylanguage
- replace rr:object with rr:objectMap
- there is no need to put \" in the rr:column vlaues

You can upload and execute this mapping on mappingpedia.

[mapping.ttl.txt](https://github.com/FacultadInformatica-LinkedData/Curso2016-2017/files/624662/mapping.ttl.txt)

**Comment by nandana** [comment]
Thanks a lot @fpriyatna !!
